import { defineConfig } from "vite-plus";
import react from "@vitejs/plugin-react";
import { sentryVitePlugin } from "@sentry/vite-plugin";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";

const rootDir = path.dirname(fileURLToPath(import.meta.url));
const clientSrc = path.resolve(rootDir, "apps/web/src/client");
const packagesDir = path.resolve(rootDir, "packages");

function getSentryRelease() {
  if (process.env.SENTRY_RELEASE) return process.env.SENTRY_RELEASE;
  const sourceVersion = process.env.SOURCE_COMMIT || process.env.SOURCE_VERSION;
  if (sourceVersion) return `groot@${sourceVersion.slice(0, 7)}`;
  try {
    const sha = execSync("git rev-parse HEAD", { encoding: "utf-8" }).trim();
    return `groot@${sha.slice(0, 7)}`;
  } catch {
    return undefined;
  }
}

const release = getSentryRelease();
const authToken = process.env.SENTRY_AUTH_TOKEN;

export default defineConfig({
  // Git hooks configuration
  staged: {
    "*": "vp check --fix",
    "*.{ts,tsx,css}": "npm run check:tokens",
  },

  // Vite build configuration - build from apps/web
  root: "apps/web",
  plugins: [
    react(),
    ...(release && authToken && process.env.SENTRY_ORG
      ? [
          sentryVitePlugin({
            authToken,
            org: process.env.SENTRY_ORG,
            project: "groot",
            sourcemaps: {
              filesToDeleteAfterUpload: ["dist/assets/*.map"],
            },
          }),
        ]
      : []),
  ],
  resolve: {
    alias: [
      {
        find: "@groot/shell/index.css",
        replacement: path.resolve(packagesDir, "shell/src/index.css"),
      },
      { find: "@groot/ui", replacement: path.resolve(packagesDir, "ui/src") },
      { find: "@groot/jobs/client", replacement: path.resolve(packagesDir, "jobs/src/client") },
      { find: "@groot/shell", replacement: path.resolve(packagesDir, "shell/src") },
      { find: "@", replacement: clientSrc },
    ],
  },
  build: {
    outDir: path.resolve(rootDir, "dist"),
    emptyOutDir: false,
    sourcemap: true,
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (
            id.includes("node_modules/react/") ||
            id.includes("node_modules/react-dom/") ||
            id.includes("node_modules/react-router-dom/")
          ) {
            return "react-vendor";
          }
        },
      },
    },
  },
  server: {
    middlewareMode: true,
    allowedHosts: process.env.PORTLESS_URL
      ? true
      : process.env.VITE_HMR_URL
        ? [process.env.VITE_HMR_URL]
        : undefined,
    ws: process.env.VITE_HMR_URL
      ? {
          protocol: "wss",
          host: process.env.VITE_HMR_URL,
          clientPort: 443,
        }
      : process.env.PORTLESS_URL
        ? (() => {
            try {
              const url = new URL(process.env.PORTLESS_URL);
              return {
                protocol: url.protocol === "https:" ? "wss" : "ws",
                host: url.hostname,
                clientPort: url.port
                  ? parseInt(url.port, 10)
                  : url.protocol === "https:"
                    ? 443
                    : 80,
              };
            } catch {
              return undefined;
            }
          })()
        : undefined,
  },
  publicDir: "./public",

  css: {
    postcss: path.resolve(rootDir, "postcss.config.js"),
  },

  // Linting configuration
  lint: {
    ignorePatterns: ["dist/**", "node_modules/**"],
  },

  // Formatting configuration
  fmt: {
    // CHANGELOG.md files are auto-generated by changesets (`changeset version`).
    // Changesets emits a blank line between a header and its following list
    // (## @groot/core\n\n- item), but Oxfmt (Prettier-compatible) collapses it
    // (## @groot/core\n- item). Excluding them avoids a format-check failure on
    // every "chore: version packages" merge — the release workflow commits the
    // raw changeset output with VITE_GIT_HOOKS=0, so the pre-commit formatter
    // never gets a chance to normalize them.
    ignorePatterns: ["**/CHANGELOG.md"],
    semi: true,
    singleQuote: false,
  },

  // Test configuration - client tests only
  // Server tests run from vitest.config.server.ts
  test: {
    include: ["../../tests/client/**/*.test.{ts,tsx}"],
    exclude: ["src/**/*.test.{ts,tsx}"],
    environment: "jsdom",
    setupFiles: ["../../tests/client/setup.ts"],
    alias: [
      { find: "@groot/ui", replacement: path.resolve(packagesDir, "ui/src") },
      { find: "@groot/jobs/client", replacement: path.resolve(packagesDir, "jobs/src/client") },
      { find: "@groot/shell", replacement: path.resolve(packagesDir, "shell/src") },
      { find: "@", replacement: clientSrc },
    ],
  },
});
