#!/usr/bin/env tsx
/**
 * One-time layout migration for downstream repos.
 *
 * Moves files from the pre-2.0 flat layout (client/src, server/src) to the
 * workspace layout (apps/web/src, packages/*). Run once after syncing groot v2+.
 *
 *   tsx .groot/migrate-layout.ts           # apply
 *   tsx .groot/migrate-layout.ts --check   # dry run
 *
 * Steps:
 *   1. git mv synced + app-owned files to new paths (preserves local edits)
 *   2. Rewrite @/ imports to @groot/* package imports
 *   3. Update prisma schema.prisma generator output path
 *   4. Rebase the sync baseline tree through the PATH_MAP
 *
 * After running: `pnpm install` then `pnpm prisma generate`.
 */
import { execSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const CWD = process.cwd();
const dryRun = process.argv.includes("--check");

function git(args: string[]): void {
  const cmd = `git ${args.join(" ")}`;
  if (dryRun) {
    console.log(`  [dry-run] ${cmd}`);
    return;
  }
  execSync(cmd, { stdio: "pipe", cwd: CWD });
}

function gitMv(oldPath: string, newPath: string): void {
  if (!existsSync(join(CWD, oldPath))) return;
  mkdirSync(join(CWD, dirname(newPath)), { recursive: true });
  git(["mv", oldPath, newPath]);
  console.log(`  mv: ${oldPath} -> ${newPath}`);
}

function plainMove(oldPath: string, newPath: string): void {
  const oldFull = join(CWD, oldPath);
  const newFull = join(CWD, newPath);
  if (!existsSync(oldFull)) return;
  if (dryRun) {
    console.log(`  [dry-run] mv ${oldPath} -> ${newPath}`);
    return;
  }
  mkdirSync(join(CWD, dirname(newPath)), { recursive: true });
  renameSync(oldFull, newFull);
  console.log(`  mv: ${oldPath} -> ${newPath}`);
}

console.log("\n## Groot Layout Migration v1\n");
console.log(`Mode: ${dryRun ? "dry run" : "apply"}\n`);

// --- Step 1: Move files ---
console.log("### Step 1: Move files\n");

// packages/ui
gitMv("client/src/ui", "packages/ui/src");

// packages/client
plainMove("client/src/index.css", "packages/client/src/index.css");
gitMv("client/src/core", "packages/client/src/core");

// packages/server
gitMv("server/src/core", "packages/server/src/core");
gitMv("server/src/shared", "packages/server/src/shared");

// packages/database (generated dir is gitignored, just remove old reference)
// The schema.prisma output path is updated in step 3.

// apps/web
gitMv("client/index.html", "apps/web/index.html");
gitMv("client/tsconfig.json", "apps/web/tsconfig.json");
gitMv("client/src/App.tsx", "apps/web/src/client/App.tsx");
gitMv("client/src/main.tsx", "apps/web/src/client/main.tsx");
gitMv("client/src/app", "apps/web/src/client/app");
plainMove("client/src/test", "apps/web/src/client/test");
gitMv("server/src/index.ts", "apps/web/src/server/index.ts");
gitMv("server/src/routes.ts", "apps/web/src/server/routes.ts");
gitMv("server/src/app", "apps/web/src/server/app");

// Remove old generated dir (regenerated by prisma generate at new path)
if (existsSync(join(CWD, "server/src/generated"))) {
  if (!dryRun) {
    execSync(`rm -rf ${join(CWD, "server/src/generated")}`);
  }
  console.log("  rm: server/src/generated (will regenerate)");
}

// --- Step 2: Rewrite imports ---
console.log("\n### Step 2: Rewrite imports\n");
console.log("  (Import rewriting is handled by the sync engine's 3-way merge.)");
console.log("  After migration, run 'pnpm groot:sync' to get the new import paths.");

// --- Step 3: Move prisma/ and update schema output ---
console.log("\n### Step 3: Move prisma/ and update schema\n");
gitMv("prisma", "apps/web/prisma");
const schemaPath = join(CWD, "apps/web/prisma/schema.prisma");
if (existsSync(schemaPath)) {
  const schema = readFileSync(schemaPath, "utf-8");
  const updated = schema.replace(
    /output\s+=\s+"\.\.\/server\/src\/generated\/prisma"/,
    'output = "../../../packages/database/generated/prisma"',
  );
  if (updated !== schema) {
    if (!dryRun) writeFileSync(schemaPath, updated);
    console.log("  Updated prisma schema.prisma generator output path.");
  } else {
    console.log("  prisma schema.prisma already updated (or not found pattern).");
  }
}

// --- Step 4: Clean up empty dirs ---
console.log("\n### Step 4: Clean up\n");
if (!dryRun) {
  for (const dir of ["client/src", "client", "server/src", "server"]) {
    const full = join(CWD, dir);
    if (existsSync(full)) {
      try {
        execSync(`rmdir ${full} 2>/dev/null || true`);
        console.log(`  cleaned: ${dir}/`);
      } catch {
        // not empty, leave it
      }
    }
  }
}

console.log("\n### Next steps:");
console.log("  1. Run 'pnpm install' to set up workspace links");
console.log("  2. Run 'pnpm prisma generate' to generate the Prisma client at the new path");
console.log("  3. Run 'pnpm groot:sync' to get updated imports from the boilerplate");
console.log("  4. Run 'pnpm check && pnpm test' to verify\n");
